version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule: { interval: weekly }
    groups:
      js-major-updates:
        patterns: ['*']
        update-types: ['major']
      js-compatible-updates:
        patterns: ['*']
        update-types: ['minor', 'patch']
  - package-ecosystem: pip
    directory: '/apps/api'
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: '/'
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: '/infra/docker'
    schedule: { interval: weekly }
