packages:
  - 'apps/web'
  - 'apps/desktop'
  - 'packages/*'

hoistPattern:
  - '*'

peerDependencyRules:
  allowedVersions:
    '@electron/fuses': '2'

overrides:
  '@electron/rebuild': '4.2.0'
  esbuild: '0.28.1'
  postcss: '8.5.19'
  tmp: '0.2.7'

allowBuilds:
  electron-winstaller: true
  esbuild: true
  sharp: true
  unrs-resolver: true
