apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loop-staging
resources:
  - ../../base

replicas:
  - name: api
    count: 2
  - name: web
    count: 2
  - name: worker
    count: 1

images:
  - name: app-api
    newName: ghcr.io/your-org/loop-agent-api
    newTag: staging
  - name: app-web
    newName: ghcr.io/your-org/loop-agent-web
    newTag: staging
  - name: app-provider-gateway
    newName: ghcr.io/your-org/loop-agent-provider-gateway
    newTag: staging

patches:
  - path: patch-config.yaml
